from telebot.handler_backends import State, StatesGroup


class UserStates(StatesGroup):
	command = State()
	language = State()
	currency = State()
	city_id = State()
	country_iso_code2 = State()
	country_iso_code3 = State()
	country = State()
	sort_order = State()
	sort_order_distance = State()
	min_distance = State()
	max_distance = State()
	min_price = State()
	max_price = State()
	check_in = State()
	check_out = State()
	count_hotel = State()
	flag_photos = State()
	count_photos = State()
	distance_from = State()
	price_from = State()
	name_key_dick = State()
	eapid = State()
	site_id = State()
	res_size = State()
	page_size = State()
